services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=kadir123'
      - 'POSTGRES_DB=InsurancePostgreSQL'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: