version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_DB: InsurancePostgreSQL
      POSTGRES_USER: kadir123
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
